### ISSUE TITLE
type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by vjk10** [jozsefsallai/dart-peekanapp#1]
![image](https://user-images.githubusercontent.com/41936318/190080459-ea20ca9c-38d1-413a-8fd9-3b11ad2fa7c6.png)

The error is thrown when fetching app details

**Comment by jozsefsallai** [comment]
Should be fixed in `peekanapp: ^0.0.2`, let me know if you still have this problem.
